CREATE DATABASE	PHPets;
USE PHPets;

CREATE TABLE CATEGORY(
CategoryID INT PRIMARY KEY,
CategoryName VARCHAR(20)
);

INSERT INTO CATEGORY VALUES
(1, 'Toys'), (2, 'Health Care'),(3,'Grooming Items'),(4,'Food'),(5, 'Accessories');

CREATE TABLE  PRODUCT(
ProductID INT PRIMARY KEY AUTO_INCREMENT,
ProductName VARCHAR(255) NOT NULL,
Description VARCHAR(500) NULL,
Price Decimal(10) NOT NULL, 
Inventory INT(10) NOT NULL,
ProductImage VARCHAR(255),
CategoryID INT,
FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID)
);

SELECT * FROM Product;
DROP TABLE Product;
ALTER TABLE Product AUTO_INCREMENT = 1;

CREATE TABLE USERTYPETABLE (
  UserType INT PRIMARY KEY,
  RoleName VARCHAR(50) NOT NULL
);

INSERT INTO USERTYPETABLE (UserType, RoleName) VALUES
(1, 'Owner'),
(2, 'Customer');
UPDATE UserTypeTable
SET RoleName = 'Customer'
WHERE UserType = 2;


CREATE TABLE USER (
  UserID INT PRIMARY KEY AUTO_INCREMENT,
  FName VARCHAR(30) NOT NULL, 
  LName VARCHAR(30) NOT NULL,
  Email VARCHAR(255) NOT NULL UNIQUE,
  Password VARCHAR(255) NOT NULL,
  UserType INT NOT NULL DEFAULT 3,
  Address VARCHAR(500) NOT NULL,
  ContactNumber BIGINT(15) NOT NULL UNIQUE,
  FailedLoginAttempts INT DEFAULT 0,
  LastFailedLogin DATETIME NULL,
  IsLocked BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (UserType) REFERENCES USERTYPETABLE(UserType)
);

ALTER TABLE USER
  ADD COLUMN FailedLoginAttempts INT DEFAULT 0,
  ADD COLUMN LastFailedLogin DATETIME NULL,
  ADD COLUMN IsLocked BOOLEAN DEFAULT FALSE;

DROP TABLE USER;

ALTER TABLE Product AUTO_INCREMENT = 3;

DELETE FROM USER WHERE UserID = '1';
SELECT * FROM USER;
DROP TABLE USER;

CREATE TABLE CART (
    CartID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    ProductID INT NOT NULL,
    InCartQuantity INT NOT NULL,
    AddedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USER(UserID) ON DELETE CASCADE,
	FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE
);

CREATE TABLE PAYMENT(
PaymentType INT PRIMARY KEY,
PaymentMethod VARCHAR(20)
);

INSERT INTO PAYMENT VALUES
(1,'Cash on Delivery');

CREATE TABLE ORDERTABLE (
    OrderID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    TotalCost DECIMAL(10, 2) NOT NULL,
    PaymentType INT NOT NULL,
    OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USER(UserID),
    FOREIGN KEY (PaymentType) REFERENCES PAYMENT(PaymentType),
    deliveryAddress VARCHAR(500),
    OrderStatus VARCHAR(20) DEFAULT 'Pending'
);

CREATE TABLE ORDERITEMS (
    OrderItemID INT PRIMARY KEY AUTO_INCREMENT,
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Subtotal DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES ORDERTABLE(OrderID),
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);

CREATE TABLE INQUIRIES (
    InquiryID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    Subject VARCHAR(255),
    Message TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(20) DEFAULT 'Open',
    FOREIGN KEY (UserID) REFERENCES USER(UserID)
);

ALTER TABLE ORDERTABLE MODIFY ArrivalDate DATETIME NULL;

DROP TABLE cart;
DROP TABLE ORDERTABLE;
DROP TABLE inquiries;
DROP TABLE ORDERITEMS;

USE PHPets;

SELECT * from UserTypeTable;
SELECT * from category;
SELECT * FROM payment;
SELECT * FROM orderitems;
SELECT * FROM ordertable;
SELECT * FROM cart;
SELECT * FROM inquiries;
SELECT * FROM user;
SELECT * FROM Product;

UPDATE USER 
SET UserID = 2
WHERE UserID = 4;
UPDATE Category SET CategoryName = 'Toys' WHERE CategoryID = '1';
